SELECT * FROM UAROPERATOR.JDA_SESSION WHERE OBJECT_ID <> '0';

SELECT * FROM UAROPERATOR.JDA_LOCK WHERE OBJECT_ID <> '0';

SELECT * FROM UAROPERATOR.DEAMON_SESSION WHERE OBJECT_ID <>  '0';

--DELETE UAROPERATOR.JDA_LOCK WHERE OBJECT_ID <> '0' ;
--DELETE UAROPERATOR.JDA_SESSION WHERE OBJECT_ID <> '0';
--DELETE UAROPERATOR.DEAMON_SESSION WHERE OBJECT_ID <> '0';
--commit;