--Buffer Pool Hit Ratio from 9.2 Perf Tune Guide and Reference (ch14)
SELECT NAME, PHYSICAL_READS, DB_BLOCK_GETS, CONSISTENT_GETS,
      1 - (PHYSICAL_READS / (DB_BLOCK_GETS + CONSISTENT_GETS)) "Hit Ratio"
 FROM V$BUFFER_POOL_STATISTICS;
