SELECT
        S1.INST_ID, S1.SID, S1.USERNAME, S1.SERIAL#, S1.SQL_ID, S1.P1TEXT||' '||S1.P1 P_1, S1.P2TEXT ||' '|| S1.P2 P_2, S1.P3TEXT ||' '|| S1.P3 P_3, S1.EVENT, S1.SECONDS_IN_WAIT,
        S2.INST_ID ||':'|| S2.SID ||':'|| S2.SERIAL# BLOCKING_USER, S1.BLOCKING_SESSION_STATUS, S2.USERNAME BLOCKING_USERNM
FROM GV$SESSION S1, GV$SESSION S2
WHERE S1.SECONDS_IN_WAIT > 60
--D (S1.EVENT LIKE '%library cache lock%' OR S1.EVENT LIKE '%library cache pin%')
AND S1.EVENT LIKE '%library cache lock%'
AND S1.INST_ID = S2.INST_ID(+)
AND S1.BLOCKING_INSTANCE = S2.INST_ID(+)
AND S1.BLOCKING_SESSION = S2.SID(+) ;