set serveroutput on size 1000000;

DECLARE
	L_M		NUMBER := 0;
	L_INST		GV$SESSION.INST_ID%TYPE;
	L_SID		GV$SESSION.SID%TYPE;
	L_SERIAL	GV$SESSION.SERIAL#%TYPE;
	L_USERNAME	GV$SESSION.USERNAME%TYPE;
	CURSOR C1
	IS
		SELECT INST_ID, SID, SERIAL#, USERNAME 
		FROM GV$SESSION 
		WHERE USERNAME = UPPER('&usernm')
--		AND UPPER(MACHINE) = UPPER('&machn')
		AND INST_ID||SID NOT IN (SELECT DISTINCT INST_ID||SID FROM GV$MYSTAT)
		AND USERNAME NOT IN ('SYS','SYSTEM','DBSNMP');
BEGIN
	OPEN C1;
	LOOP
		FETCH C1 INTO L_INST, L_SID, L_SERIAL, L_USERNAME;
		EXIT WHEN C1%NOTFOUND;
		DBMS_OUTPUT.PUT_LINE('ALTER SYSTEM KILL SESSION '''||TO_CHAR(L_SID)||','||TO_CHAR(L_SERIAL)||',@'||TO_CHAR(L_INST)||''' IMMEDIATE;');
--		BEGIN
--			EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION '''||L_SID||','||L_SERIAL||'@'||TO_CHAR(L_INST)||''' IMMEDIATE';
--		EXCEPTION
--			when others then L_M := 0;
--		END;
	END LOOP;
END;
/

undef killsid
undef killserial
undef killinst
