SET PAGES 68 LINES 110
SET FEEDBACK OFF

SPOOL newobjs.lst

TTITLE "OBJECTS CREATED IN THE DATABASE DURING THE PAST WEEK"

COL OBJECT_TYPE FORMAT A20
COL OBJECT_NAME FORMAT A40
COL OWNER       FORMAT A18
COL DATE_CREATED HEADING "CREATED ON"

BREAK ON DATE_CREATED NODUP

SELECT to_char(created,'mm/dd/yyyy hh24:mi') as date_created, owner, object_name, object_type, status
FROM dba_objects
WHERE created >= (SYSDATE - 7)
ORDER BY created desc;
--ORDER BY object_type, name;


SPOOL OFF
TTITLE OFF
CLEAR COLUMNS
SET FEEDBACK ON
