col owner format a12
col referenced_owner format a12
col name format a24
col referenced_name format a24
col type format a10
col referenced_type format a10
col path format a32

ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/YYYY HH24:MI:SS';

WITH X AS
(
   SELECT D.OWNER, D.NAME, D.TYPE, D.REFERENCED_OWNER, D.REFERENCED_NAME, D.REFERENCED_TYPE, O.LAST_DDL_TIME, O.STATUS 
   FROM DBA_DEPENDENCIES D JOIN DBA_OBJECTS O 
        ON (O.OWNER = D.REFERENCED_OWNER) 
        AND (O.OBJECT_NAME = D.REFERENCED_NAME) 
        AND (O.OBJECT_TYPE = D.REFERENCED_TYPE)     
)
SELECT --OWNER, NAME, TYPE,
	REFERENCED_OWNER,
	REFERENCED_NAME,
	REFERENCED_TYPE,
	LEVEL,
	LPAD(' ',(LEVEL-1)*5) || REFERENCED_OWNER ||'.'|| REFERENCED_NAME PATH,
	LAST_DDL_TIME, STATUS,
	case when (last_ddl_time > sysdate-1) then 'X' else ' ' end RECENT
FROM X
START WITH OWNER = 'BRAVURA' and NAME = 'TRG_MMP_BU_1'
CONNECT BY PRIOR REFERENCED_NAME = NAME AND PRIOR REFERENCED_OWNER = OWNER and PRIOR REFERENCED_TYPE = TYPE
ORDER SIBLINGS BY NAME;
