SELECT GRANTEE, GRANTED_GROUP, GRANT_OPTION, INITIAL_GROUP, INITIAL_RSRC_CONSUMER_GROUP, PROFILE, USERNAME
FROM DBA_RSRC_CONSUMER_GROUP_PRIVS, DBA_USERS
WHERE GRANTEE(+) = USERNAME
AND username = upper('&usernm')
ORDER BY GRANTED_GROUP;
