column retention format a12

SELECT
  DBID,
  EXTRACT(DAY FROM SNAP_INTERVAL)*24*60 + EXTRACT(HOUR FROM SNAP_INTERVAL)*60 + EXTRACT(MINUTE FROM SNAP_INTERVAL) SNAPSHOT_INTERVAL_MIN,
  EXTRACT(DAY FROM RETENTION)*24*60     + EXTRACT(HOUR FROM RETENTION)*60     + EXTRACT(MINUTE FROM RETENTION)     RETENTION_INTERVAL_MIN,
  EXTRACT(DAY FROM RETENTION)||'d '||EXTRACT(HOUR FROM RETENTION)||'h '||EXTRACT(MINUTE FROM RETENTION)||'m' RETENTION,
  TOPNSQL
FROM DBA_HIST_WR_CONTROL
WHERE DBID = (SELECT DBID FROM V$DATABASE);
