set linesize 180;
COLUMN COMPATIBILITY FORMAT A12;
COLUMN DATABASE_COMPATIBILITY FORMAT A12;
COLUMN NAME  FORMAT a12;

SELECT GROUP_NUMBER, NAME, SECTOR_SIZE, BLOCK_SIZE, ALLOCATION_UNIT_SIZE, STATE, TYPE, TOTAL_MB, FREE_MB, USABLE_FILE_MB, COMPATIBILITY, DATABASE_COMPATIBILITY, VOTING_FILES
FROM V$ASM_DISKGROUP;
