set linesize 132;

COLUMN SOURCE_DATABASE FORMAT A16;
COLUMN ERROR_MESSAGE FORMAT A26;
COLUMN APPLY_NAME FORMAT A18;
COLUMN LOCAL_TRANSACTION_ID FORMAT A17;
COLUMN MESSAGE_NUMBER FORMAT 99999;
COLUMN SOURCE_COMMIT_SCN FORMAT 999999999999999;

ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/YYYY HH24:MI:SS';

SELECT  LOCAL_TRANSACTION_ID, -- as "Local Transx ID",
        APPLY_NAME,
--        QUEUE_OWNER,
--        QUEUE_NAME,
--        SOURCE_DATABASE,
        SOURCE_COMMIT_SCN,
        MESSAGE_NUMBER as "MSG NBR",
        ERROR_MESSAGE,
        MESSAGE_COUNT as "MSG CNT",
        ERROR_CREATION_TIME
FROM dba_apply_error;
