COLUMN SENDER_NAME       HEADING 'Capture|Process'         FORMAT A16
COLUMN SENDER_ADDRESS    HEADING 'Sender|Queue'            FORMAT A16
COLUMN QUEUE_SCHEMA      HEADING 'Queue Owner'             FORMAT A18
COLUMN QUEUE_NAME        HEADING 'Queue Name'              FORMAT A28
COLUMN CNUM_MSGS         HEADING 'Number|of LCRs|Enqueued' FORMAT 99999999
COLUMN LAST_ENQUEUED_MSG HEADING 'Last|Enqueued|LCR'       FORMAT 9999999999
COLUMN MEMORY_USAGE      HEADING 'Streams|Pool|% Used'     FORMAT 999
COLUMN PUBLISHER_STATE   HEADING 'Publisher state'         FORMAT A32
COLUMN UNBROWSED_MSGS    HEADING '# Enqueued|Not Browsed' 
COLUMN OVERSPILLED_MSGS  HEADING '# Spilled|Not Browsed' 
  
SELECT
--QUEUE_ID,
QUEUE_SCHEMA,
QUEUE_NAME,
SENDER_NAME,
NVL(SENDER_ADDRESS,'(local)') SENDER_ADDRESS,
--SENDER_PROTOCOL,
NUM_MSGS,
CNUM_MSGS,
LAST_ENQUEUED_MSG,
UNBROWSED_MSGS,
OVERSPILLED_MSGS,
MEMORY_USAGE,
PUBLISHER_STATE
FROM gV$BUFFERED_PUBLISHERS;
