COLUMN APPLY_NAME FORMAT A18 HEADING 'Apply name';
COLUMN SOURCE_DATABASE FORMAT A18 HEADING 'Source DB';
COLUMN APPLIED_MESSAGE_NUMBER FORMAT 999999999999999 HEADING 'Applied Msg Nbr';
COLUMN OLDEST_MESSAGE_NUMBER FORMAT 999999999999999  HEADING 'Oldest Msg Nbr';
COLUMN APPLY_TIME HEADING 'Apply time';
COLUMN APPLIED_MESSAGE_CREATE_TIME HEADING 'Applied message|create time';
COLUMN OLDEST_TRANSACTION_ID FORMAT A18 HEADING 'Oldest transaction ID';
COLUMN STATUS HEADING 'Status';
COLUMN STATUS_CHANGE_TIME HEADING 'Status Chg Time';
COLUMN SPILL_MESSAGE_NUMBER FORMAT 999999999999999  HEADING 'Spill Msg Nbr';

prompt
prompt  Apply status
prompt ==============

SELECT APPLY_NAME, STATUS, STATUS_CHANGE_TIME FROM DBA_APPLY;


prompt
prompt
prompt  Apply progress
prompt ================

SELECT * FROM DBA_APPLY_PROGRESS;


prompt
prompt  Apply error
prompt =============

SELECT * FROM DBA_APPLY_ERROR;


prompt
prompt  Heartbeat monitor (last 5)
prompt ============================


COLUMN DB_NAME FORMAT A12             HEADING 'Source DB';
COLUMN SRC_SCN FORMAT 999999999999999 HEADING 'Source DB SCN';
COLUMN SRC_TS                         HEADING 'Source DB timestamp';
COLUMN TGT_SCN FORMAT 999999999999999 HEADING 'Target DB SCN';
COLUMN TGT_TS                         HEADING 'Target DB timestamp';

SELECT *
FROM
	(
		SELECT *
		FROM STREAMS_ADMIN.STREAMS_HEARTBEAT_MONITOR 
		ORDER BY TGT_SCN DESC
	) 
WHERE ROWNUM < 6;

TTITLE OFF;
