COLUMN QUEUE_SCHEMA HEADING 'Queue|Owner' FORMAT A14
COLUMN QUEUE_NAME HEADING 'Queue|Name' FORMAT A24
COLUMN DST_QUEUE_SCHEMA HEADING 'Destination|Queue|Owner' FORMAT A11
COLUMN DST_QUEUE_NAME HEADING 'Destination|Queue|Name' FORMAT A11
COLUMN STARTUP_TIME HEADING 'Startup Time'
COLUMN DBLINK HEADING 'Database|Link' FORMAT A10
COLUMN SCHEDULE_STATUS HEADING 'Schedule Status' FORMAT A20
COLUMN TOTAL_MSGS  HEADING 'Total|Messages|Propagated'
COLUMN TOTAL_MB    HEADING 'Total|MB|Propagated' FORMAT 999999.9999 
COLUMN ELAPSED_DEQUEUE_TIME HEADING 'Elapsed|Dequeue|Time (s)'
COLUMN ELAPSED_PICKLE_TIME HEADING 'Elapsed|Pickle|Time (s)'
COLUMN ELAPSED_PROPAGATION_TIME HEADING 'Elapsed|Propagation|Time (s)'
COLUMN HIGH_WATER_MARK HEADING 'High|Water|Mark'
COLUMN ACKNOWLEDGEMENT HEADING 'Acknowledge-|ment by|Receiver'

SELECT
--QUEUE_ID,
QUEUE_SCHEMA,
QUEUE_NAME,
DST_QUEUE_SCHEMA,
DST_QUEUE_NAME,
STARTUP_TIME,
DBLINK,
HIGH_WATER_MARK,
ACKNOWLEDGEMENT,
SCHEDULE_STATUS,
TOTAL_MSGS,
(TOTAL_BYTES/(1024*1024)) TOTAL_MB,
ELAPSED_DEQUEUE_TIME/100 ELAPSED_DEQUEUE_TIME,
ELAPSED_PICKLE_TIME/100 ELAPSED_PICKLE_TIME,
ELAPSED_PROPAGATION_TIME/100 ELAPSED_PROPAGATION_TIME
--MAX_NUM_PER_WIN,
--MAX_SIZE
FROM V$PROPAGATION_SENDER;


COLUMN PROPAGATION_NAME        HEADING 'Propagation' FORMAT A22
COLUMN SOURCE_QUEUE_OWNER      HEADING 'Source|Queue Owner' FORMAT A14
COLUMN SOURCE_QUEUE_NAME       HEADING 'Source|Queue Name' FORMAT A32
COLUMN DESTINATION_QUEUE_OWNER HEADING 'Destination|Queue Owner' FORMAT A14
COLUMN DESTINATION_QUEUE_NAME  HEADING 'Destination|Queue Name' FORMAT A28
COLUMN RULE_SET                HEADING 'Rule Set' FORMAT A28
COLUMN NEGATIVE_RULE_SET_OWNER HEADING 'Negatve|RuleSet|Owner' FORMAT A8
COLUMN NEGATIVE_RULE_SET_NAME  HEADING 'Negatve|RuleSet|Name' FORMAT A8
COLUMN ERROR_MESSAGE           HEADING 'Error Message' FORMAT A24
COLUMN ERROR_DATE              HEADING 'Error Date'
COLUMN STATUS                  HEADING 'Status'

SELECT
PROPAGATION_NAME,
SOURCE_QUEUE_OWNER,
SOURCE_QUEUE_NAME || '@' || GLOBAL_NAME SOURCE_QUEUE_NAME,
DESTINATION_QUEUE_OWNER,
DESTINATION_QUEUE_NAME || '@' || DESTINATION_DBLINK DESTINATION_QUEUE_NAME, 
RULE_SET_OWNER ||'.'|| RULE_SET_NAME RULE_SET,
NEGATIVE_RULE_SET_OWNER,
NEGATIVE_RULE_SET_NAME,
--QUEUE_TO_QUEUE,
STATUS,
ERROR_MESSAGE,
ERROR_DATE
FROM DBA_PROPAGATION, GLOBAL_NAME;
