SELECT * FROM GV$LOG ORDER BY INST_ID, GROUP#;

--member, status, type
SELECT * FROM GV$LOGFILE ORDER BY INST_ID, GROUP#;

SELECT
  L.INST_ID, L.GROUP#, L.THREAD#, L.SEQUENCE#, L.BYTES, L.BLOCKSIZE, L.MEMBERS, L.ARCHIVED, L.STATUS, L.FIRST_CHANGE#, L.FIRST_TIME, L.NEXT_CHANGE#, L.NEXT_TIME,
  LF.MEMBER, LF.STATUS, LF.TYPE
FROM GV$LOG L, GV$LOGFILE LF
WHERE L.INST_ID = LF.INST_ID
AND L.GROUP# = LF.GROUP#
ORDER BY L.INST_ID, L.GROUP#;

ALTER SESSION SET NLS_DATE_FORMAT = 'mm/dd/yyyy hh24:mi:ss';

SELECT
  L.GROUP#, L.THREAD#, L.SEQUENCE#, L.BYTES, L.BLOCKSIZE, L.MEMBERS, L.ARCHIVED, L.STATUS, L.FIRST_CHANGE#, L.FIRST_TIME, L.NEXT_CHANGE#, L.NEXT_TIME,
  LF.MEMBER, LF.STATUS, LF.TYPE
FROM V$LOG L, V$LOGFILE LF
WHERE L.GROUP# = LF.GROUP#
ORDER BY L.GROUP#, L.THREAD#, LF.MEMBER;

SELECT * FROM DBA_TAB_COLUMNS WHERE COLUMN_NAME = 'FILE_ID';

SELECT * FROM DBA_DATA_FILES    ORDER BY FILE_ID DESC;
SELECT * FROM DBA_TEMP_FILES    ORDER BY FILE_ID DESC;
SELECT * FROM DBA_ROLLBACK_SEGS ORDER BY FILE_ID DESC;
SELECT * FROM DBA_UNDO_EXTENTS  ORDER BY FILE_ID DESC;