SELECT *
FROM DBA_SCHEDULER_JOB_LOG
WHERE JOB_NAME = 'FLAT_ODS_LOAD_RUN'
ORDER BY LOG_DATE DESC;

SELECT *
FROM DBA_SCHEDULER_JOB_RUN_DETAILS
WHERE JOB_NAME = 'FLAT_ODS_LOAD_RUN'
ORDER BY LOG_DATE DESC;

SELECT *
FROM DBA_SCHEDULER_JOBS
WHERE OWNER = 'DW_FLATODS'
AND JOB_NAME = 'FLAT_ODS_LOAD_RUN';

SELECT ENABLED, a.*
FROM DBA_SCHEDULER_CHAINS a
WHERE OWNER = 'DW_FLATODS' 
AND CHAIN_NAME = 'FLAT_ODS_LOAD';

SELECT *
FROM DBA_SCHEDULER_CHAIN_RULES
WHERE OWNER = 'DW_FLATODS'
AND CHAIN_NAME = 'LPS_INTERFACES'
ORDER BY RULE_NAME;

SELECT *
FROM DBA_SCHEDULER_CHAIN_STEPS
WHERE OWNER = 'DW_FLATODS'
AND CHAIN_NAME = 'CATCHUP_RETAIL_CHAIN'
ORDER BY STEP_NAME;

SELECT *
FROM DBA_SCHEDULER_RUNNING_CHAINS 
WHERE OWNER = 'DW_FLATODS' 
AND JOB_NAME = 'RUN_CATCHUP_RETAIL_CHAIN_01'
ORDER BY START_DATE, END_DATE NULLS LAST ;


/*
SELECT * FROM DBA_HIST_SQLSTAT JOIN DBA_HIST_SNAPSHOT USING (SNAP_ID, INSTANCE_NUMBER) WHERE SQL_ID = 'g1r9gyd2rj13m' ORDER BY SNAP_ID DESC;

SELECT * FROM DBA_SCHEDULER_WINDOWS;

SELECT DISTINCT OWNER, CHAIN_NAME
FROM DBA_SCHEDULER_CHAIN_RULES
MINUS
SELECT DISTINCT OWNER, CHAIN_NAME
FROM DBA_SCHEDULER_CHAIN_RULES
WHERE CONDITION = 'TRUE';

SELECT * FROM DBA_RULESETS WHERE RULESET_NAME = 'SCHED_RULESET$11';
*/