SELECT *
FROM DBA_SCHEDULER_JOB_LOG
WHERE JOB_NAME = 'BRAV_CRF_LOAD_JOB'
ORDER BY LOG_DATE DESC;

SELECT *
FROM DBA_SCHEDULER_JOB_RUN_DETAILS
WHERE JOB_NAME = 'BRAV_CRF_LOAD_JOB'
ORDER BY LOG_DATE DESC;

SELECT *
FROM DBA_SCHEDULER_JOBS
WHERE OWNER = 'DW_ODS'
AND JOB_NAME = 'BRAV_CRF_LOAD_JOB';

SELECT * FROM DBA_OBJECTS WHERE OBJECT_NamE = 'PR_CRF_BRAV_LOAN';

select * from dba_programs;

SELECT ENABLED, a.*
FROM DBA_SCHEDULER_CHAINS a
WHERE OWNER = 'DW_ODS' 
AND CHAIN_NAME = 'BRAV_CRF_LOAD_CHAIN';

SELECT *
FROM DBA_SCHEDULER_CHAIN_RULES
WHERE OWNER = 'DW_ODS'
AND CHAIN_NAME = 'BRAV_CRF_LOAD_CHAIN'
ORDER BY RULE_NAME;

SELECT *
FROM DBA_SCHEDULER_CHAIN_STEPS
WHERE OWNER = 'DW_ODS'
AND CHAIN_NAME = 'BRAV_CRF_LOAD_CHAIN'
ORDER BY STEP_NAME;

SELECT *
FROM DBA_SCHEDULER_RUNNING_CHAINS 
WHERE OWNER = 'DW_ODS' 
AND JOB_NAME = 'BRAV_CRF_LOAD_JOB'
ORDER BY START_DATE, END_DATE NULLS LAST ;


/*
SELECT * FROM DBA_HIST_SQLSTAT JOIN DBA_HIST_SNAPSHOT USING (SNAP_ID, INSTANCE_NUMBER) WHERE SQL_ID = 'g1r9gyd2rj13m' ORDER BY SNAP_ID DESC;

SELECT * FROM DBA_SCHEDULER_WINDOWS;

SELECT DISTINCT OWNER, CHAIN_NAME
FROM DBA_SCHEDULER_CHAIN_RULES
MINUS
SELECT DISTINCT OWNER, CHAIN_NAME
FROM DBA_SCHEDULER_CHAIN_RULES
WHERE CONDITION = 'TRUE';

SELECT * FROM DBA_RULESETS WHERE RULESET_NAME = 'SCHED_RULESET$11';
*/