SELECT * FROM DBA_USERS WHERE USERNAME = 'DW_DRM_APPID';
SELECT * FROM DBA_USERS WHERE USERNAME LIKE '%_APPID' ORDER BY USERNAME;
  
SELECT P.PROFILE, P.RESOURCE_NAME, P.RESOURCE_TYPE, P.LIMIT, CASE P.LIMIT WHEN 'DEFAULT' THEN D.LIMIT ELSE P.LIMIT END EFFECTIVE_LIMIT
FROM DBA_PROFILES P, DBA_PROFILES D
WHERE P.RESOURCE_NAME = D.RESOURCE_NAME
AND P.PROFILE = 'PROFILE_APP_USER'
AND D.PROFILE = 'DEFAULT'
ORDER BY P.RESOURCE_TYPE, P.RESOURCE_NAME;

SELECT P.PROFILE, P.RESOURCE_NAME, P.RESOURCE_TYPE, P.LIMIT, CASE P.LIMIT WHEN 'DEFAULT' THEN D.LIMIT ELSE P.LIMIT END EFFECTIVE_LIMIT
FROM DBA_PROFILES P, DBA_PROFILES D
WHERE P.RESOURCE_NAME = D.RESOURCE_NAME
AND P.PROFILE = 'PROFILE_CON_POOL'
AND D.PROFILE = 'DEFAULT'
ORDER BY P.RESOURCE_TYPE, P.RESOURCE_NAME;

SELECT * FROM DBA_RSRC_CONSUMER_GROUPS WHERE CONSUMER_GROUP = 'DEFAULT_CONSUMER_GROUP';
SELECT * FROM DBA_RSRC_CONSUMER_GROUPS WHERE CONSUMER_GROUP = 'FS_APPLICATION_GROUP';
SELECT * FROM DBA_RSRC_CONSUMER_GROUPS WHERE CONSUMER_GROUP = 'FS_BIEE_GROUP';
SELECT * FROM DBA_RSRC_CONSUMER_GROUP_PRIVS;
SELECT * FROM DBA_RSRC_PLAN_DIRECTIVES;

SELECT ST.*, N.NAME
FROM GV$SESSTAT ST, V$STATNAME N
WHERE ST.STATISTIC# = N.STATISTIC#
AND EXISTS (SELECT 1 FROM GV$SESSION SE WHERE SE.USERNAME = 'DW_DRM_APPID' AND SE.INST_ID = ST.INST_ID AND SE.SID = ST.SID)
AND VALUE > 0;

SELECT SE.INST_ID, SE.SID, SE.USERNAME, SE.STATUS, SE.RESOURCE_CONSUMER_GROUP, ST.VALUE, N.NAME
FROM GV$SESSTAT ST, V$STATNAME N, GV$SESSION SE
WHERE ST.STATISTIC# = N.STATISTIC#
AND ST.INST_ID = SE.INST_ID
AND ST.SID = SE.SID
AND SE.USERNAME = 'DW_DRM_APPID'
AND ST.VALUE > 0;




SELECT NAME, IS_TOP_PLAN FROM V$RSRC_PLAN;

SELECT NAME, ACTIVE_SESSIONS, QUEUE_LENGTH, CONSUMED_CPU_TIME, CPU_WAITS, CPU_WAIT_TIME FROM V$RSRC_CONSUMER_GROUP;