exec dbaudit.set_dba_role('');



CREATE USER FSBMON
  IDENTIFIED BY VALUES '6A7B6F2DF1CB9F60'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  ACCOUNT UNLOCK;

GRANT RESTRICTED SESSION TO FSBMON;
GRANT CREATE SESSION TO FSBMON;
GRANT SELECT ANY DICTIONARY TO FSBMON;

GRANT SELECT ON DBAUDIT.LOGON_AUDIT_TABLE TO FSBMON;
GRANT SELECT ON APEX.CPUSUMMARY  TO FSBMON;
GRANT SELECT ON APEX.PATROLAGENT TO FSBMON;
