select * from DBA_HIST_SQLSTAT where snap_id;

SELECT * FROM DBA_HIST_SNAPSHOT
WHERE DBID = (SELECT DBID FROM V$DATABASE)
and end_interval;


SELECT * FROM DBA_HIST_SQLSTAT JOIN DBA_HIST_SNAPSHOT USING (SNAP_ID, INSTANCE_NUMBER) WHERE SQL_ID = 'grx7hsy11djsc' ORDER BY SNAP_ID DESC;

SELECT * FROM DBA_HIST_SQLSTAT JOIN DBA_HIST_SNAPSHOT USING (SNAP_ID, INSTANCE_NUMBER) WHERE SQL_ID = '5785m6a07698f' ORDER BY SNAP_ID DESC;

SELECT * FROM DBA_HIST_SQL_PLAN WHERE SQL_ID = 'grx7hsy11djsc';

SELECT * FROM DBA_HIST_SQL_PLAN WHERE SQL_ID = '5785m6a07698f';
SELECT * FROM DBA_HIST_SQL_PLAN WHERE SQL_ID = '9d3547bvgpux6';
9d3547bvgpux6

select * from DBA_HIST_SQL_PLAN;

SELECT * FROM DBA_HIST_SESS_TIME_STATS;

SELECT * FROM DBA_HIST_ACTIVE_SESS_HISTORY 
WHERE SAMPLE_TIME >= TO_TIMESTAMP ('2013-09-26 11:30:00','YYYY-MM-DD HH24:MI:SS')
  AND SAMPLE_TIME <= TO_TIMESTAMP ('2013-09-26 12:00:00','YYYY-MM-DD HH24:MI:SS');
  
  
SELECT SQL_ID, COUNT(*), ROUND(COUNT(*) / SUM(COUNT(*)) OVER (), 2) PCTLOAD
FROM DBA_HIST_ACTIVE_SESS_HISTORY 
WHERE SAMPLE_TIME >= TO_TIMESTAMP ('2013-09-26 11:30:00','YYYY-MM-DD HH24:MI:SS')
  AND SAMPLE_TIME <= TO_TIMESTAMP ('2013-09-26 12:00:00','YYYY-MM-DD HH24:MI:SS')
AND SESSION_TYPE <> 'BACKGROUND'
GROUP BY SQL_ID
ORDER BY COUNT(*) DESC;

alter session set nls_date_format = 'mm/dd/yyyy hh24:mi:ss';

SELECT TRUNC(TO_DATE('01011970','ddmmyyyy')+A.F_TIMESTAMP*(1/24/60/60)) THETMSP, A.* FROM F_SW.VWLOG2_1048 A WHERE TRUNC(TO_DATE('01011970','ddmmyyyy')+F_TIMESTAMP*(1/24/60/60))<= TO_DATE('06/30/2012','mm/dd/yyyy');

--01/25/2010 00:00:00
SELECT MIN ( TRUNC(TO_DATE('01011970','ddmmyyyy')+F_TIMESTAMP*(1/24/60/60))  )
FROM F_SW.VWLOG2_1048;

SELECT MIN ( TRUNC(TO_DATE('01011970','ddmmyyyy')+F_TIMESTAMP*(1/24/60/60))  )
FROM F_SW.VWLOG1_129;




SELECT *
  FROM v$transaction vt;
  
SELECT * FROM V$FAST_START_TRANSACTIONS;


SELECT OWNER, SEGMENT_NAME, TABLESPACE_NAME, BYTES/(1024*1024*1024) SIZEGB, EXTENTS
FROM DBA_SEGMENTS
WHERE OWNER = 'F_SW'
AND SEGMENT_NAME = 'VWLOG1_129';

select * from F_SW.VWLOG1_129;

SELECT OWNER, SEGMENT_NAME, TABLESPACE_NAME, BYTES/(1024*1024*1024) SIZEGB, EXTENTS
FROM DBA_SEGMENTS
WHERE OWNER = 'F_SW'
AND SEGMENT_NAME = 'VWLOG2_1048';

select count(*) from F_SW.VWLOG2_1048;


select row_wait_obj#, row_wait_file#, row_wait_row# from v$session where sid = 845;

select * from v$sysstat;

SELECT * FROM GV$SYSTEM_EVENT order by time_waited_micro desc;


select owner, segment_name, segment_type, bytes/(1024*1024*1024) sizeGB from dba_segments where tablespace_name = 'ORACLE_DB0' order by bytes desc;