SELECT *
FROM   DW_COMMON.PROGRAM_DEBUG_LOG 
WHERE  DEBUG_DATE = TRUNC(SYSDATE)
--AND    DEBUG_MESSAGE_STR LIKE 'FLAT_ODS_LOAN_LOAD%' 
ORDER BY update_date DESC;

ALTER SESSION SET NLS_DATE_FORMAT = 'mm/dd/yyyy hh24:mi:ss';
ALTER SESSION SET NLS_DATE_FORMAT = 'dd-MON-yyyy';

SELECT PROGRAM_LOG_SEQ, DEBUG_MESSAGE_STR, DEBUG_DATE, NVL(TO_CHAR(UPDATE_DATE,'mm/dd/yyyy hh24:mi:ss'),'<null>') UPDATE_DATE, UPDATE_USER_STR
FROM   DW_COMMON.PROGRAM_DEBUG_LOG 
WHERE  DEBUG_DATE = '01-OCT-2011'
AND DEBUG_MESSAGE_STR LIKE 'FLAT_ODS_LOAN_LOAD%'
ORDER BY update_date DESC;


--==============================================================================
SELECT * FROM DW_META.PROGRAM_LOG WHERE PROGRAM_ID = 'TCBS_GL_LOAD' ORDER BY PROGRAM_LOG_SEQ DESC;
SELECT * FROM DW_META.PROCESS_LOG WHERE PROGRAM_LOG_SEQ = 603398    ORDER BY PROCESS_LOG_SEQ DESC;

SELECT * FROM DW_META.PROGRAM_LOG 
ORDER BY PROGRAM_LOG_SEQ DESC;

SELECT * FROM DW_META.PROCESS_LOG
WHERE PROGRAM_LOG_SEQ = 628404
ORDER BY PROCESS_LOG_SEQ DESC;