SELECT * FROM OL$;
SELECT * FROM OL$HINTS;
SELECT * FROM OL$NODES;
SELECT * FROM DBA_OUTLINES;
SELECT DISTINCT CATEGORY FROM DBA_OUTLINES;

SELECT * FROM DBA_OUTLINE_HINTS;
--DBMS_OUTLN
--DBMS_OUTLN_EDIT

SELECT OUTLINE_CATEGORY, OUTLINE_SID FROM V$SQL WHERE OUTLINE_CATEGORY IS NOT NULL;

--http://download.oracle.com/docs/cd/B19306_01/server.102/b14211/outlines.htm
--CREATE ANY OUTLINE PRIVILEGE
--ALTER SESSION SET CREATE_STORED_OUTLINES =
--ALTER SESSION SET USE_STORED_OUTLINES