ALTER SESSION SET NLS_DATE_FORMAT = 'mm/dd/yyyy hh24:mi:ss';

SELECT * FROM GV$SQL WHERE SQL_ID = '3gt10yvb11uu7';
SELECT * FROM GV$SQLAREA WHERE SQL_ID = '3gt10yvb11uu7';

SELECT ADDRESS, HASH_VALUE, SQL_ID, SQL_TEXT
, CASE WHEN INSTR(LOWER(SQL_TEXT), 'insert') > 0 THEN 'INSERT' ELSE ' ' END AS INS
, CASE WHEN INSTR(LOWER(SQL_TEXT), 'select') > 0 THEN 'SELECT' ELSE ' ' END AS SEL
, CASE WHEN INSTR(LOWER(SQL_TEXT), 'from')   > 0 THEN 'FROM'   ELSE ' ' END AS FRO
, CASE WHEN INSTR(LOWER(SQL_TEXT), 'where')  > 0 THEN 'WHERE'  ELSE ' ' END as WHE
FROM V$SQLTEXT 
WHERE SQL_ID = '3gt10yvb11uu7' 
ORDER BY SQL_ID, PIECE;

SELECT * FROM DBA_TAB_COLUMNS WHERE COLUMN_NAME = 'BIND_DATA';

EXEC DBAUDIT.SET_DBA_ROLE('DBA20130530');

SELECT /*+ parallel( src, 4 ) */ PROD_DATE, DATA_SRC_ID, ACCT_NUM, ACCT_TYPE, REC_TYPE, ACCR_FEE_AMT, ACCR_INT_AMT, ACCR_INT_PRIOR_NP_AMT, ACCT_REP_FULL_NAME_STR, ACCT_STAT_CODE, ACH_CHOICE_AMT, ACH_CODE, ACTL_CLS_DATE, ADP_CODE, AGENCY_CASE_ID, AH_CLS_COST_AMT, AH_CLS_COST_SRC_CODE, AH_DOWN_PYMT_AMT, AH_DOWN_PYMT_SRC_CODE, AMORT_MAT_DATE, AMORT_TERM_NUM, AMORT_TYPE, ANN_DECR_CAP_PCT, ANN_INCR_CAP_PCT, APPL_TAKEN_DATE, APR_SPREAD_PCT, APRV_DATE, ASSET_DATE, ASUM_CODE, AVAIL_CRED_LIMIT_AMT, AVG_ESCR_BAL_AMT, BASE_CORP_MARGIN_RATE_PCT, BASE_LOAN_AMT, BASE_SRP_RATE_PCT, BD_AMT, BD_FLAG, BILL_ADDR_CITY_STR, BILL_ADDR_LINE_1_STR, BILL_ADDR_LINE_2_STR, BILL_ADDR_POSTAL_CODE, BILL_ADDR_STATE_PROV_CODE, BRANCH_CODE, BUS_CHAN_CODE, BUS_CHAN_MARGIN_RATE_PCT, BUY_PRICE_NUM, BV_SVC_AMT, CEIL_RATE_PCT, CHRG_OFF_FEE_AMT, CHRG_OFF_INT_AMT, CHRG_OFF_PRIN_AMT, CLOSE_DATE, CLTV_PCT, CLTV_W_PREM_PCT, COLLECTOR_CODE, COLLECTOR_QUEUE_CODE, COMMUNITY_PGM_FLAG, CONS_LOAN_TYPE, CONSTR_ESCR_AMT, CONSTR_OWNER_DEP_AMT, CONVERTIBLE_FLAG, COUPON_BILL_LAST_CREATE_DATE, CRA_CODE, CRED_LIMIT_AMT, CRED_RPT_CODE, CRED_SCORE_NUM, CURTAIL_AMT, DD_ACCT_NUM, DEBT_RSTRC_FLAG, DELINQ_120_DAYS_NUM, DELINQ_30_DAYS_NUM, DELINQ_60_DAYS_NUM, DELINQ_90_DAYS_NUM, DELINQ_CODE, DFLT_STAT_CODE, DFR_COST_AMT, DFR_FEE_AMT, DFR_INC_AMT, DFR_INT_AMT, DISB_DATE, DOC_TYPE, DU_CASE_ID, DU_RESPONSE_CODE, DU_VER_STR, ECLS_STAT_CODE, EMP_LOAN_CODE, ESCR_BAL_AMT, ESCR_CODE, EST_CLS_DATE, EXCESS_SVC_AMT, EXCESS_SVC_DATE, EXCESS_SVC_INV_STR, FAS_COST_AMT, FAS_FEE_AMT, FEE_AMT, FEE_BILL_AMT, FILE_LOCATION_CODE, FIRST_PYMT_CHG_DATE, FIRST_PYMT_DATE, FIRST_RATE_CHG_DATE, FIRST_TIME_HOME_BUYER_FLAG, FLOOR_RATE_PCT, FNMA_PLAN_CODE, FRBR_AMT, FULL_INDEX_PCT, LAST_UPDATE_DATE, SRC_DELETE_FLAG, BILL_ADDR_FOREIGN_CODE, DFLT_STAT_DATE, DELINQ_REASON_CODE, DELINQ_OFFICE_CODE, DELINQ_CLASS_CODE, DELINQ_LM_IND, BKPT_CODE, BKPT_CHANGE_DATE, FRCLS_CODE, FRCLS_CHANGE_DATE, DRAFT_EFF_DATE, CUM_FAIR_VAL_ADJ_AMT, ACCT_TREATMENT_TYPE, CORP_ADV_RECOV_AMT, CORP_ADV_NONRECOV_AMT, CORP_3RDPARTY_AMT, CONSTR_TERM_NUM, APPL_REGISTER_DATE, CONTROL_CODE, ESCR_SHORT_AMT, BACKEND_RATIO_PCT, CHRG_OFF_STAT_CODE, CHRG_OFF_AMT, CHRG_OFF_REASON_CODE, CHRG_OFF_DATE, ARM_RND_PCT, ESCR_MTH_LIEN_AMT, ESCR_MTH_CNTY_AMT, ESCR_MTH_CITY_AMT, DNSL_SUB_REASON_STR, CLOSE_NAME_TYPE, CEMA_LOAN_FLAG, CEMA_LOAN_ID 
FROM TABLE(
            DW_CRF.PKG_BRAV_CRF_LOAD_LOAN_1.SF_RETURN_LOAN_DATA ( :B1 , :B2 , :B3 , CURSOR(SELECT MTG_SK_SEQ FROM DW_CRF.DIRTIED_MORTGAGE WHERE PROCESSING_ROW_NUM BETWEEN :B5 AND :B4 )
          )
) SRC;

SELECT COUNT(*) FROM DW_CRF.DIRTIED_MORTGAGE;

select * from gv$session where username = 'KNAUSS_DBA';