SELECT * FROM DBA_SCHEDULER_JOBS WHERE JOB_NAME = 'MSR_APECS_DONE_FILE_JOB';

SELECT REQ_START_DATE, ACTUAL_START_DATE, (ACTUAL_START_DATE-REQ_START_DATE)
FROM DBA_SCHEDULER_JOB_RUN_DETAILS
WHERE JOB_NAME = 'MSR_APECS_DONE_FILE_JOB'
ORDER BY LOG_DATE DESC;

SELECT * FROM DBA_SCHEDULER_GLOBAL_ATTRIBUTE WHERE ATTRIBUTE_NAME = 'CURRENT_OPEN_WINDOW';

SELECT * --WINDOW_NAME, REPEAT_INTERVAL 
FROM DBA_SCHEDULER_WINDOWS;