SELECT EVENT, WAIT_CLASS, TOTAL_WAITS, TIME_WAITED_MICRO/1000000 T
FROM V$SYSTEM_EVENT
ORDER BY TIME_WAITED_MICRO DESC;
--==============================================================================
SELECT PROGRAM_LOG_SEQ, PROGRAM_ID, JOB_NAME_STR, PROGRAM_START_TS, PROGRAM_END_TS, UPDATE_DATE, UPDATE_USER_STR, (PROGRAM_END_TS-PROGRAM_START_TS)
FROM DW_COMMON.PROGRAM_LOG
WHERE UPDATE_DATE > (SYSDATE -14)
AND PROGRAM_ID like '%FLAT%'
ORDER BY UPDATE_DATE DESC;

SELECT *
FROM DW_COMMON.PROGRAM_ACTIVITY_LOG
WHERE PROGRAM_LOG_SEQ = 62448
ORDER BY CREATE_TS DESC;

SELECT *
FROM DW_COMMON.PROGRAM_DEBUG_LOG
WHERE DEBUG_DATE > (SYSDATE - 3)
AND PROGRAM_LOG_SEQ = 62448
ORDER BY UPDATE_DATE DESC;
--==============================================================================
SELECT * --OWNER, JOB_NAME, JOB_SUBNAME, SESSION_ID, SLAVE_PROCESS_ID, SLAVE_OS_PROCESS_ID, RUNNING_INSTANCE, ELAPSED_TIME
FROM DBA_SCHEDULER_RUNNING_JOBS;

SELECT LOG_ID, LOG_DATE, OWNER, JOB_NAME, JOB_SUBNAME, OPERATION, STATUS, ADDITIONAL_INFO
FROM DBA_SCHEDULER_JOB_LOG 
WHERE JOB_NAME = 'FLAT_ODS_LOAD_RUN' AND LOG_DATE > (SYSDATE - 2)
ORDER BY LOG_DATE DESC;

SELECT OWNER, JOB_NAME, JOB_SUBNAME, STATUS, RUN_DURATION, INSTANCE_ID, SESSION_ID, ADDITIONAL_INFO
FROM DBA_SCHEDULER_JOB_RUN_DETAILS
WHERE JOB_NAME = 'FLAT_ODS_LOAD_RUN'
ORDER BY LOG_DATE DESC;

SELECT * FROM DBA_SCHEDULER_CHAIN_STEPS WHERE STEP_NAME = 'S5_ML_FLAT_COLLATERAL';

SELECT * FROM DBA_SCHEDULER_PROGRAMS WHERE PROGRAM_NAME = 'PR_LD_ML_FLAT_COLLATERAL';

SELECT * FROM DBA_OBJECTS WHERE OBJECT_NAME = 'PKG_FLAT_SC_LOAN_LOAD';


SELECT INST_ID, EVENT, WAIT_CLASS, COUNT(*)
FROM GV$SESSION_WAIT
WHERE STATE = 'WAITING'
GROUP BY INST_ID, EVENT, WAIT_CLASS
ORDER BY 4 DESC;