--8tk2z4jj99qbx

BEGIN
  DBAUDIT.SET_DBA_ROLE('DBA20130715');
END;
/

SELECT LOAN_NUMBER, LOAN_PURPOSE, LOAN_TYPE, CLOSING_DATE, OCCUPANCY_TYPE, GUARANTOR_TYPE, APPRAISED_VALUE, MERS_NUMBER, INTERIM_FUNDER_STATUS, INTERIM_FUNDER_STATUS_DATE, FHA_DELEGATED_FLAG, COLLATERAL_PKG_SHIP_DATE, SHIP_TRACKING_NUM, BORROWER_FIRST_NAME, BORROWER_MIDDLE_NAME, BORROWER_LAST_NAME, BORROWER_SSN, PROPERTY_ADDDRESS_LINE1, BORROWER_CITY, BORROWER_STATE, BORROWER_ZIP, NOTE_AMOUNT, NOTE_DATE, TYPE, CORRESPONDENT_ID, DRAW_FEE, AGENT_NAME, AGENT_TYPE, AGENT_ADDRESS_LINE1, AGENT_CITY, AGENT_STATE, AGENT_ZIP, AGENT_PHONE, AGENT_FAX, CONTACT_SK_SEQ, CTA_SEQ_NUM, INVESTOR_ID, INVESTOR_CONTACT_ID, INVESTOR_ADDRESS_ID, CONTACT, DATE_EXPECTED, ADVANCE_REQUEST_AMOUNT, TOTAL_WIRE_TRANSFER_AMOUNT, CREDIT_TO, ACCOUNT_NUMBER, FURTHER_CREDIT, FURTHER_CREDIT_ACCOUNT, BANK_NAME, BANK_ABA, BANK_ADDRESS, BANK_STATE, BANK_CITY, BANK_ZIP, BANK_PHONE, CHECK_NUMBER, CHECK_AMOUNT, REMARKS, COMMENTS, STATUS_NUM, TERMS_ACCEPTED, INVESTOR_TYPE, CREATEDATE, MODIFYDATE, DATE_RECEIVED, ADVANCE_REQUEST_DATE, RECEIVED_BY, MODIFY_USER, CONFIRMATION_NUMBER, LTV,DTI,CREDIT_SCORE,BASE_LOAN_AMT,ECLOSING_FLAG,PRODUCT_DESC,OTHER_PROD_DESC, ADVANCE_ID, IMAD_NUMBER, ADVANCE_AMOUNT, PAYMENT_AMOUNT, INTRANET.SF_GET_ADVANCE_STATUS(NULL, TO_CHAR(CORRESPONDENT_ID) || '-' || CONFIRMATION_NUMBER) ADVANCE_STATUS,
(select description
from intranet.code_lookup
where code_type = 'INTMFUNDST' and code = interim_funder_status) INTERIM_FUNDER_STATUS_DESC
FROM INTRANET.ADVANCE
WHERE LOAN_NUMBER LIKE :1 AND INVESTOR_ID <> '2' AND (STATUS_NUM = '2' OR (STATUS_NUM = '3' AND TERMS_ACCEPTED = '0')) UNION
SELECT LOAN_NUMBER, LOAN_PURPOSE, LOAN_TYPE, CLOSING_DATE, OCCUPANCY_TYPE, GUARANTOR_TYPE, APPRAISED_VALUE, MERS_NUMBER, INTERIM_FUNDER_STATUS, INTERIM_FUNDER_STATUS_DATE, FHA_DELEGATED_FLAG, COLLATERAL_PKG_SHIP_DATE, SHIP_TRACKING_NUM, BORROWER_FIRST_NAME, BORROWER_MIDDLE_NAME, BORROWER_LAST_NAME, BORROWER_SSN, PROPERTY_ADDDRESS_LINE1, BORROWER_CITY, BORROWER_STATE, BORROWER_ZIP, NOTE_AMOUNT, NOTE_DATE, TYPE, CORRESPONDENT_ID, DRAW_FEE, AGENT_NAME, AGENT_TYPE, AGENT_ADDRESS_LINE1, AGENT_CITY, AGENT_STATE, AGENT_ZIP, AGENT_PHONE, AGENT_FAX, CONTACT_SK_SEQ, CTA_SEQ_NUM, INVESTOR_ID, INVESTOR_CONTACT_ID, INVESTOR_ADDRESS_ID, CONTACT, DATE_EXPECTED, ADVANCE_REQUEST_AMOUNT, TOTAL_WIRE_TRANSFER_AMOUNT, CREDIT_TO, ACCOUNT_NUMBER, FURTHER_CREDIT, FURTHER_CREDIT_ACCOUNT, BANK_NAME, BANK_ABA, BANK_ADDRESS, BANK_STATE, BANK_CITY, BANK_ZIP, BANK_PHONE, CHECK_NUMBER, CHECK_AMOUNT, REMARKS, COMMENTS, STATUS_NUM, TERMS_ACCEPTED, INVESTOR_TYPE, CREATEDATE, MODIFYDATE, DATE_RECEIVED, ADVANCE_REQUEST_DATE, RECEIVED_BY, MODIFY_USER, CONFIRMATION_NUMBER, LTV,DTI,CREDIT_SCORE,BASE_LOAN_AMT,ECLOSING_FLAG,PRODUCT_DESC,OTHER_PROD_DESC, ADVANCE_ID, IMAD_NUMBER, ADVANCE_AMOUNT, PAYMENT_AMOUNT, INTRANET.SF_GET_ADVANCE_STATUS(NULL, TO_CHAR(CORRESPONDENT_ID) || '-' || CONFIRMATION_NUMBER) ADVANCE_STATUS,
(select description
from intranet.code_lookup
where code_type = 'INTMFUNDST' and code = interim_funder_status) INTERIM_FUNDER_STATUS_DESC
FROM INTRANET.ADVANCE
WHERE LOAN_NUMBER = :2 AND INVESTOR_ID = '2' AND STATUS_NUM = '2';
--==============================================================================
SELECT LOAN_NUMBER, LOAN_PURPOSE, LOAN_TYPE, CLOSING_DATE, OCCUPANCY_TYPE, GUARANTOR_TYPE, APPRAISED_VALUE, MERS_NUMBER, INTERIM_FUNDER_STATUS, INTERIM_FUNDER_STATUS_DATE, FHA_DELEGATED_FLAG, COLLATERAL_PKG_SHIP_DATE, SHIP_TRACKING_NUM, BORROWER_FIRST_NAME, BORROWER_MIDDLE_NAME, BORROWER_LAST_NAME, BORROWER_SSN, PROPERTY_ADDDRESS_LINE1, BORROWER_CITY, BORROWER_STATE, BORROWER_ZIP, NOTE_AMOUNT, NOTE_DATE, TYPE, CORRESPONDENT_ID, DRAW_FEE, AGENT_NAME, AGENT_TYPE, AGENT_ADDRESS_LINE1, AGENT_CITY, AGENT_STATE, AGENT_ZIP, AGENT_PHONE, AGENT_FAX, CONTACT_SK_SEQ, CTA_SEQ_NUM, INVESTOR_ID, INVESTOR_CONTACT_ID, INVESTOR_ADDRESS_ID, CONTACT, DATE_EXPECTED, ADVANCE_REQUEST_AMOUNT, TOTAL_WIRE_TRANSFER_AMOUNT, CREDIT_TO, ACCOUNT_NUMBER, FURTHER_CREDIT, FURTHER_CREDIT_ACCOUNT, BANK_NAME, BANK_ABA, BANK_ADDRESS, BANK_STATE, BANK_CITY, BANK_ZIP, BANK_PHONE, CHECK_NUMBER, CHECK_AMOUNT, REMARKS, COMMENTS, STATUS_NUM, TERMS_ACCEPTED, INVESTOR_TYPE, CREATEDATE, MODIFYDATE, DATE_RECEIVED, ADVANCE_REQUEST_DATE, RECEIVED_BY, MODIFY_USER, CONFIRMATION_NUMBER, LTV,DTI,CREDIT_SCORE,BASE_LOAN_AMT,ECLOSING_FLAG,PRODUCT_DESC,OTHER_PROD_DESC, ADVANCE_ID, IMAD_NUMBER, ADVANCE_AMOUNT, PAYMENT_AMOUNT, INTRANET.SF_GET_ADVANCE_STATUS(NULL, TO_CHAR(CORRESPONDENT_ID) || '-' || CONFIRMATION_NUMBER) ADVANCE_STATUS
FROM INTRANET.ADVANCE
WHERE LOAN_NUMBER LIKE :1 
AND INVESTOR_ID <> '2' 
AND (STATUS_NUM = '2' OR (STATUS_NUM = '3' AND TERMS_ACCEPTED = '0'));
--==============================================================================
SELECT LOAN_NUMBER, LOAN_PURPOSE, LOAN_TYPE, CLOSING_DATE, OCCUPANCY_TYPE, GUARANTOR_TYPE, APPRAISED_VALUE, MERS_NUMBER, INTERIM_FUNDER_STATUS, INTERIM_FUNDER_STATUS_DATE, FHA_DELEGATED_FLAG, COLLATERAL_PKG_SHIP_DATE, SHIP_TRACKING_NUM, BORROWER_FIRST_NAME, BORROWER_MIDDLE_NAME, BORROWER_LAST_NAME, BORROWER_SSN, PROPERTY_ADDDRESS_LINE1, BORROWER_CITY, BORROWER_STATE, BORROWER_ZIP, NOTE_AMOUNT, NOTE_DATE, TYPE, CORRESPONDENT_ID, DRAW_FEE, AGENT_NAME, AGENT_TYPE, AGENT_ADDRESS_LINE1, AGENT_CITY, AGENT_STATE, AGENT_ZIP, AGENT_PHONE, AGENT_FAX, CONTACT_SK_SEQ, CTA_SEQ_NUM, INVESTOR_ID, INVESTOR_CONTACT_ID, INVESTOR_ADDRESS_ID, CONTACT, DATE_EXPECTED, ADVANCE_REQUEST_AMOUNT, TOTAL_WIRE_TRANSFER_AMOUNT, CREDIT_TO, ACCOUNT_NUMBER, FURTHER_CREDIT, FURTHER_CREDIT_ACCOUNT, BANK_NAME, BANK_ABA, BANK_ADDRESS, BANK_STATE, BANK_CITY, BANK_ZIP, BANK_PHONE, CHECK_NUMBER, CHECK_AMOUNT, REMARKS, COMMENTS, STATUS_NUM, TERMS_ACCEPTED, INVESTOR_TYPE, CREATEDATE, MODIFYDATE, DATE_RECEIVED, ADVANCE_REQUEST_DATE, RECEIVED_BY, MODIFY_USER, CONFIRMATION_NUMBER, LTV,DTI,CREDIT_SCORE,BASE_LOAN_AMT,ECLOSING_FLAG,PRODUCT_DESC,OTHER_PROD_DESC, ADVANCE_ID, IMAD_NUMBER, ADVANCE_AMOUNT, PAYMENT_AMOUNT, INTRANET.SF_GET_ADVANCE_STATUS(NULL, TO_CHAR(CORRESPONDENT_ID) || '-' || CONFIRMATION_NUMBER) ADVANCE_STATUS,
(select description
from intranet.code_lookup
where code_type = 'INTMFUNDST' and code = interim_funder_status) INTERIM_FUNDER_STATUS_DESC
FROM INTRANET.ADVANCE
WHERE LOAN_NUMBER = :2 AND INVESTOR_ID = '2' AND STATUS_NUM = '2';
--==============================================================================
/*
2	219120
3	58
*/
SELECT STATUS_NUM, COUNT(*)
FROM INTRANET.ADVANCE
WHERE INVESTOR_ID <> '2'
AND (STATUS_NUM = '2' OR (STATUS_NUM = '3' AND TERMS_ACCEPTED = '0'))
group by STATUS_NUM;


--867121
select count(*) from  INTRANET.ADVANCE;

SELECT * FROM DBA_TABLES WHERE OWNER = 'INTRANET' AND TABLE_NAME = 'ADVANCE';

SELECT * FROM DBA_INDEXES WHERE OWNER = 'INTRANET' AND INDEX_NAME = 'IDX_ADVANCE_2';

alter session set nls_date_format = 'mm/dd/yyyy hh24:mi:ss';

select * from v$sql_plan where sql_id = '8tk2z4jj99qbx';

select * from table(dbms_xplan.DISPLAY_CURSOR('8tk2z4jj99qbx'));

--==============================================================================
EXPLAIN PLAN SET STATEMENT_ID = 'ktk2'
FOR
SELECT LOAN_NUMBER, LOAN_PURPOSE, LOAN_TYPE, CLOSING_DATE, OCCUPANCY_TYPE, GUARANTOR_TYPE, APPRAISED_VALUE, MERS_NUMBER, INTERIM_FUNDER_STATUS, INTERIM_FUNDER_STATUS_DATE, FHA_DELEGATED_FLAG, COLLATERAL_PKG_SHIP_DATE, SHIP_TRACKING_NUM, BORROWER_FIRST_NAME, BORROWER_MIDDLE_NAME, BORROWER_LAST_NAME, BORROWER_SSN, PROPERTY_ADDDRESS_LINE1, BORROWER_CITY, BORROWER_STATE, BORROWER_ZIP, NOTE_AMOUNT, NOTE_DATE, TYPE, CORRESPONDENT_ID, DRAW_FEE, AGENT_NAME, AGENT_TYPE, AGENT_ADDRESS_LINE1, AGENT_CITY, AGENT_STATE, AGENT_ZIP, AGENT_PHONE, AGENT_FAX, CONTACT_SK_SEQ, CTA_SEQ_NUM, INVESTOR_ID, INVESTOR_CONTACT_ID, INVESTOR_ADDRESS_ID, CONTACT, DATE_EXPECTED, ADVANCE_REQUEST_AMOUNT, TOTAL_WIRE_TRANSFER_AMOUNT, CREDIT_TO, ACCOUNT_NUMBER, FURTHER_CREDIT, FURTHER_CREDIT_ACCOUNT, BANK_NAME, BANK_ABA, BANK_ADDRESS, BANK_STATE, BANK_CITY, BANK_ZIP, BANK_PHONE, CHECK_NUMBER, CHECK_AMOUNT, REMARKS, COMMENTS, STATUS_NUM, TERMS_ACCEPTED, INVESTOR_TYPE, CREATEDATE, MODIFYDATE, DATE_RECEIVED, ADVANCE_REQUEST_DATE, RECEIVED_BY, MODIFY_USER, CONFIRMATION_NUMBER, LTV,DTI,CREDIT_SCORE,BASE_LOAN_AMT,ECLOSING_FLAG,PRODUCT_DESC,OTHER_PROD_DESC, ADVANCE_ID, IMAD_NUMBER, ADVANCE_AMOUNT, PAYMENT_AMOUNT, INTRANET.SF_GET_ADVANCE_STATUS(NULL, TO_CHAR(CORRESPONDENT_ID) || '-' || CONFIRMATION_NUMBER) ADVANCE_STATUS,
(select description
from intranet.code_lookup
where code_type = 'INTMFUNDST' and code = interim_funder_status) INTERIM_FUNDER_STATUS_DESC
FROM INTRANET.ADVANCE
WHERE LOAN_NUMBER LIKE :1 AND INVESTOR_ID <> '2' AND (STATUS_NUM = '2' OR (STATUS_NUM = '3' AND TERMS_ACCEPTED = '0')) UNION
SELECT LOAN_NUMBER, LOAN_PURPOSE, LOAN_TYPE, CLOSING_DATE, OCCUPANCY_TYPE, GUARANTOR_TYPE, APPRAISED_VALUE, MERS_NUMBER, INTERIM_FUNDER_STATUS, INTERIM_FUNDER_STATUS_DATE, FHA_DELEGATED_FLAG, COLLATERAL_PKG_SHIP_DATE, SHIP_TRACKING_NUM, BORROWER_FIRST_NAME, BORROWER_MIDDLE_NAME, BORROWER_LAST_NAME, BORROWER_SSN, PROPERTY_ADDDRESS_LINE1, BORROWER_CITY, BORROWER_STATE, BORROWER_ZIP, NOTE_AMOUNT, NOTE_DATE, TYPE, CORRESPONDENT_ID, DRAW_FEE, AGENT_NAME, AGENT_TYPE, AGENT_ADDRESS_LINE1, AGENT_CITY, AGENT_STATE, AGENT_ZIP, AGENT_PHONE, AGENT_FAX, CONTACT_SK_SEQ, CTA_SEQ_NUM, INVESTOR_ID, INVESTOR_CONTACT_ID, INVESTOR_ADDRESS_ID, CONTACT, DATE_EXPECTED, ADVANCE_REQUEST_AMOUNT, TOTAL_WIRE_TRANSFER_AMOUNT, CREDIT_TO, ACCOUNT_NUMBER, FURTHER_CREDIT, FURTHER_CREDIT_ACCOUNT, BANK_NAME, BANK_ABA, BANK_ADDRESS, BANK_STATE, BANK_CITY, BANK_ZIP, BANK_PHONE, CHECK_NUMBER, CHECK_AMOUNT, REMARKS, COMMENTS, STATUS_NUM, TERMS_ACCEPTED, INVESTOR_TYPE, CREATEDATE, MODIFYDATE, DATE_RECEIVED, ADVANCE_REQUEST_DATE, RECEIVED_BY, MODIFY_USER, CONFIRMATION_NUMBER, LTV,DTI,CREDIT_SCORE,BASE_LOAN_AMT,ECLOSING_FLAG,PRODUCT_DESC,OTHER_PROD_DESC, ADVANCE_ID, IMAD_NUMBER, ADVANCE_AMOUNT, PAYMENT_AMOUNT, INTRANET.SF_GET_ADVANCE_STATUS(NULL, TO_CHAR(CORRESPONDENT_ID) || '-' || CONFIRMATION_NUMBER) ADVANCE_STATUS,
(select description
from intranet.code_lookup
where code_type = 'INTMFUNDST' and code = interim_funder_status) INTERIM_FUNDER_STATUS_DESC
FROM INTRANET.ADVANCE
WHERE LOAN_NUMBER = :2 AND INVESTOR_ID = '2' AND STATUS_NUM = '2';

SELECT cardinality "Rows", lpad(' ',level-1)||operation||' '||options||' '||object_name "Plan", p.*
  FROM PLAN_TABLE p
CONNECT BY prior id = parent_id
        AND prior statement_id = statement_id
  START WITH ID = 0
        AND STATEMENT_ID = 'ktk2'
  ORDER BY id;
  
  
select ADDRESS, HASH_VALUE from V$SQLAREA where SQL_ID like '8tk2z4jj99qbx';


exec sys.DBMS_SHARED_POOL.PURGE ('0700000029EF6948, 1653922173', 'C');